// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADGPMf2Hyk5aWP4s2hnG6vz_MAFBC4AJs',
    appId: '1:221971215007:web:338a1559a50d16f877a8aa',
    messagingSenderId: '221971215007',
    projectId: 'booking-room-82921',
    authDomain: 'booking-room-82921.firebaseapp.com',
    storageBucket: 'booking-room-82921.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS32ZMDKun-dbRukoXk7Y3h90WPiL2N3o',
    appId: '1:221971215007:android:01615f2e412c61f477a8aa',
    messagingSenderId: '221971215007',
    projectId: 'booking-room-82921',
    storageBucket: 'booking-room-82921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbDpTng0QB0_uNxM7fgZOPzjkSUnOyz_c',
    appId: '1:221971215007:ios:be1114e69b9e664277a8aa',
    messagingSenderId: '221971215007',
    projectId: 'booking-room-82921',
    storageBucket: 'booking-room-82921.appspot.com',
    iosClientId: '221971215007-6vsemnjpug1okd42p2oatd2dbkukkrr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.new99',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbDpTng0QB0_uNxM7fgZOPzjkSUnOyz_c',
    appId: '1:221971215007:ios:be1114e69b9e664277a8aa',
    messagingSenderId: '221971215007',
    projectId: 'booking-room-82921',
    storageBucket: 'booking-room-82921.appspot.com',
    iosClientId: '221971215007-6vsemnjpug1okd42p2oatd2dbkukkrr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.new99',
  );
}
